#!/bin/bash
#
# Copyright 2019 Joyent, Inc.
#
# Run a given net-agent integration test.
# Run `./runtests -h` for usage info.
#

set -o errexit

TOP=$(unset CDPATH; cd $(dirname $0)/../; pwd)
TAPE="${TOP}/node_modules/.bin/tape"
NODE="${TOP}/node/bin/node"

function usage
{
    echo "Usage:"
    echo "  runtest [OPTIONS...] file"
    echo ""
    echo "Options:"
    echo "  -h Print this help and exit."
}

while getopts "h:" opt
do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

# Should have only one argument left.
if [[ $OPTIND -ne $# ]]; then
    usage
    exit 1
fi

shift $(($OPTIND - 1))
$NODE $TAPE $1
