#!/bin/bash
#
# Rsync net-agent
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
#else
#    # Clean node_modules everytime.
#    ssh $NODE rm -rf /zones/$SDC_ZONE/root/opt/smartdc/sdc/node_modules/imgapi-cli/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/var/tmp/net-agent/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /deps/ \
    --exclude /docs/ \
    --exclude /tools/ \
    --exclude /tmp/

ssh $NODE cp -R /opt/smartdc/agents/lib/node_modules/vm-agent/node_modules/ /var/tmp/net-agent/